name: minecraft_compass
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+4

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.6
  firebase_app_check: ^0.3.2+6

  # Google Sign In
  google_sign_in: ^6.2.2

  # Navigation
  go_router: ^15.1.2

  # State Management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # Map & Location & Compass
  geolocator: ^14.0.1
  flutter_compass: ^0.8.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  flutter_map_animations: ^0.9.0

  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Other utilities
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.15
  flutter_gen_runner:

# dart run build_runner build --delete-conflicting-outputs

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# This section is specific to Flutter Gen, a code generator for Flutter assets.
flutter_gen:
  output: lib/config

# Flutter Native Splash configuration
# Cấu hình Splash Screen với icon PNG trong suốt
flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#000000"  
  image: assets/icons/splash_icon.png

  android_12:
    image: assets/icons/splash_icon_android12.png
