// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzaQr8PICJ5SlYFj9hr5lcZyPFnBz-jkE',
    appId: '1:812751773442:web:d71a11339a1738776a2c1b',
    messagingSenderId: '812751773442',
    projectId: 'minecraft-compass',
    authDomain: 'minecraft-compass.firebaseapp.com',
    storageBucket: 'minecraft-compass.firebasestorage.app',
    measurementId: 'G-54LJ48VMCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFAAThd9EHGcKSIP0yAlT-Dju1zXUBUhg',
    appId: '1:812751773442:android:72f4712a6f6385336a2c1b',
    messagingSenderId: '812751773442',
    projectId: 'minecraft-compass',
    storageBucket: 'minecraft-compass.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ7LTq-xaBYD4h-JG88dGst8DaJK8OpV8',
    appId: '1:812751773442:ios:6398e9ab5e02191c6a2c1b',
    messagingSenderId: '812751773442',
    projectId: 'minecraft-compass',
    storageBucket: 'minecraft-compass.firebasestorage.app',
    androidClientId:
        '812751773442-t0cpsmtgg8uvn3p2p7lkn3usflno1hua.apps.googleusercontent.com',
    iosClientId:
        '812751773442-02375spu8b997kiogj2dfk2iaier1a6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.minecraftCompass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ7LTq-xaBYD4h-JG88dGst8DaJK8OpV8',
    appId: '1:812751773442:ios:6398e9ab5e02191c6a2c1b',
    messagingSenderId: '812751773442',
    projectId: 'minecraft-compass',
    storageBucket: 'minecraft-compass.firebasestorage.app',
    androidClientId:
        '812751773442-t0cpsmtgg8uvn3p2p7lkn3usflno1hua.apps.googleusercontent.com',
    iosClientId:
        '812751773442-02375spu8b997kiogj2dfk2iaier1a6l.apps.googleusercontent.com',
    iosBundleId: 'com.example.minecraftCompass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzaQr8PICJ5SlYFj9hr5lcZyPFnBz-jkE',
    appId: '1:812751773442:web:8f3eb33edab8808f6a2c1b',
    messagingSenderId: '812751773442',
    projectId: 'minecraft-compass',
    authDomain: 'minecraft-compass.firebaseapp.com',
    storageBucket: 'minecraft-compass.firebasestorage.app',
    measurementId: 'G-SX0YR0950B',
  );
}
